### ISSUE TITLE
uBluetooth or bluetooth

### ISSUE THREAD

**Issue by DaHoopster** [BradenM/micropy-stubs#9]
I am using a M5Stack Fire with SPRAM for development. I installed the stub `esp32-micropython-1.12.0`, but I am unable to find either `network.Bluetooth` class or the top-level `ubluetooth` class mentioned by the [official MicroPython doc](https://docs.micropython.org/en/latest/library/ubluetooth.html) from the VS Code code autocomplete. Could you help me understand what went wrong? Thanks

**Comment by lemariva** [comment]
You don't find that on the board, or as autocompletion suggestion? because FYI: the M5Stack micropython firmware doesn't have the BLE module included. It is a fork from loboris/MicroPython_ESP32_psRAM_LoBo. I wrote an article about it: https://lemariva.com/blog/2020/02/m5stack-micropython-and-bluetooth-ble

**Comment by BradenM** [comment]
Hi @DaHoopster, sorry for the delay.

Looked into this, and it seems that the current version of [Josverl/micropython-stubber](https://github.com/Josverl/micropython-stubber) does not currently make an attempt to generate stubs for the bluetooth module (as can be seen [here](https://github.com/Josverl/micropython-stubber/blob/ccd73538dde8a5da77b89aba79c0d7a076e5eecd/createstubs.py#L80))

I would recommend creating an issue on Joverl/micropython-stubber about this to see about adding the bluetooth module to the "to stub" list (or to inquire why it was left out if intentional)

**Comment by DaHoopster** [comment]
Got it, thanks @BradenM

**Comment by askpatrickw** [comment]
I opened an issue with a proposed PR

https://github.com/Josverl/micropython-stubber/issues/13
